notfirstapp/urls.py
from django.conf.urls import patterns, url, include
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from notfirstapp import views

urlpatterns = patterns('',
	#login
	url(r'^login/$','django.contrib.auth.views.login', {'template_name': 'notfirstapp/loginframe.html'},name="LoginPage"),
	url(r'^logout/$','django.contrib.auth.views.logout', {'template_name': 'notfirstapp/logout.html'},name="LogoutPage"),
	#signup
	url(r'^signup/$',views.SignUpView.as_view(),name='SignUpPage'),
	url(r'^profile/$',views.ProfileView.as_view(),name='ProfilePage'),
	#index page
	url(r'^$', views.IndexView.as_view(), name="indexPage"),
	# url(r'^(?P<game_id>\d+)/$', views.DetailPageController, name='DetailPage'),
	#game part
	url(r'^game/upload/$',login_required(views.GameCreateView.as_view()),name='GameFormPage'),
	url(r'^game/(?P<pk>\d+)/$',login_required(views.GameDetailView.as_view()),name='GameDetailPage'),
	url(r'^game/$',login_required(views.GameListView.as_view()),name='GameListPage'),
	url(r'^game/(?P<pk>\d+)/rank/$',login_required(views.ScoreRankView.as_view()),name='ScoreRankPage'),
	url(r'^game/simplelist/$',TemplateView.as_view(template_name='game.html'),name='SimpleGameListPage'),
	#image part
	url(r'^image/upload/$',login_required(views.ImageView.as_view()),name='ImageFormPage'),
	url(r'^image/(?P<pk>\d+)/$',views.ImageDetailView.as_view(),name='ImageDetailPage'),
	url(r'^image/$',views.ImageListView.as_view(),name='ImageListPage'),

	#api part ScoreRankApiView
	url(r'^rank/(?P<pk>\d+)/$',views.ScoreRankApiView,name='ScoreRankApi'),

	#2048 game demo
	url(r'^2048/$',TemplateView.as_view(template_name='notfirstapp/2048.html'),name='GameDemoPage'),
	# url(r'^(?P<contact_id>\d+)/edit/$', views.EditPageController, name='EditPage'),
	# url(r'^(?P<contact_id>\d+)/edit/done$', views.EditDoneController, name='EditDone'),
	# url(r'^create/$', views.CreatePageController, name='CreatePage'),
	# url(r'^create/done$', views.CreateDoneController, name='CreateDone'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

notfirstapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Account(models.Model):
	firstname = models.CharField(max_length=50,blank=1,null=1)
	lastname = models.CharField(max_length=50,blank=1,null=1)
	username = models.CharField(max_length=50)
	def __unicode__(self):
		return self.username
	def isGameDeveloper(self):
		return len(Own.objects.filter(Account_id=self))>0
	isGameDeveloper.boolean=1
	isGameDeveloper.short_description='Game Developer?'

class Game(models.Model):
	gamename=models.CharField(max_length=100,default="Game")
	createTime=models.DateTimeField(auto_now_add=1)
	fk_image=models.ForeignKey('Image',null=True)
	"""docstring for Game"""
	def __unicode__(self):
		return self.gamename
	
class Figure(models.Model):
	name=models.CharField(max_length=50,default="Player")
	tag=models.CharField(max_length=50,default="Player#0000")
	User_id=models.ForeignKey(User)
	def __unicode__(self):
		return self.name+"\t tag: "+self.tag
				

class Play(models.Model):
	"""docstring for Play"""
	# User_id=models.ForeignKey(User)
	Game_id=models.ForeignKey(Game)
	Figure_id=models.ForeignKey(Figure)
	def __unicode__(self):
		return "Playing "+self.Game_id.gamename+" as "+self.Figure_id.name

class Own(models.Model):
	Game_id=models.ForeignKey(Game)
	User_id=models.ForeignKey(User)
	"""docstring for GameOwner"""
	def __unicode__(self):
		# username = Account.objects.filter(id=self.Account_id)[0].username
		# gamename = Game.objects.filter(id=self.Account_id)[0].username
		return self.User_id.username+" owns "+self.Game_id.gamename
		
class ScoreRank(models.Model):
	Figure_id=models.ForeignKey(Figure)
	Game_id=models.ForeignKey(Game)
	score=models.IntegerField(default=0)
	rank=models.IntegerField(default=0)
	achieveTime=models.DateTimeField(auto_now_add=1)
	"""docstring for Rank"""
	def __unicode__(self):
		return self.Figure_id.name+" got "+ str(self.score)+" at "+str(self.achieveTime)+" and ranks at "+str(self.rank if self.rank!=0 else 'N/A')

class TimeRank(models.Model):
	Figure_id=models.ForeignKey(Figure)
	Game_id=models.ForeignKey(Game)
	finishTime=models.TimeField(auto_now_add=0)
	rank=models.IntegerField(default=0)
	achieveTime=models.DateTimeField(auto_now_add=1)
	"""docstring for TimeRank"""
	def __unicode__(self):
		return self.Figure_id.name+" finished game in "+ str(self.finishTime)+" at "+str(self.achieveTime)+" and ranks at "+str(self.rank if self.rank!=0 else 'N/A')

class Image(models.Model):
    imagefile = models.ImageField(upload_to='Images/%Y/%m/%d')	

    def __unicode__(self):
		return self.imagefile.url
		
	

notfirstapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class AccountForm(forms.ModelForm):
    password= models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    # newUser=None

    class Meta:
        model=Account


    def is_valid(self):
        # import pdb; pdb.set_trace();
        emptyError='This field is required'
        isFilledUp=True
        flag=super(AccountForm,self).is_valid()
        #check all field is filled up
        if not bool(self.data['username']):
            self.errors['username']=emptyError
        if not bool(self.data['password']):
            self.errors['password']=emptyError
        # if not bool(self.data['email']):
        #     self.errors['email']=emptyError
        if len(self.errors)==0:
            #check if username is valid
            existList=[user.username for user in User.objects.all()]
            if self.data['username'] in existList:
                self.errors['Invaild Username']='Username has been used by someone else!'
                isFilledUp=False
        else:#fail to find all required info
            isFilledUp=False
        # import pdb; pdb.set_trace()
        return flag and isFilledUp

    def save(self):
        user=User.objects.create_user(
            username=self.data['username'],
            password=self.data['password'],
            email=self.data['email'],
            first_name=self.data['firstname'],
            last_name=self.data['lastname']
        )
        self.newUser=user

class GameForm(forms.ModelForm):
    class Meta:
    	model= Game
        field=['gamename','fk_image']

    # def send_email(self):
    #     # send email using the self.cleaned_data dictionary
    #     pass

class ImageForm(forms.Form):
    imagefile = forms.ImageField(
        label='Select a image',
        help_text='max. 42 megabytes'
    )

class FigureForm(forms.ModelForm):
    class Meta:
        model=Figure
        field=['name']

class PlayForm(forms.ModelForm):
    class Meta:
        model=Play

class ScoreRankForm(forms.ModelForm):
    # username=models.CharField(max_length=50)
    # playername=models.CharField(max_length=50)
    # gamename=models.CharField(max_length=50)
    class Meta:
        model=ScoreRank
        exclude=['rank']

notfirstapp/templates/notfirstapp/2048.html
 {% load staticfiles%}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>2048</title>

  <link href={%static "notfirstapp/css/main.css"%} rel="stylesheet" type="text/css">
  <link href={% static "notfirstapp/css/colorbox.css"%} rel="stylesheet">
  <link rel="shortcut icon" href={% static "notfirstapp/favicon.ico"%}>
</head>
<body>
  <div class="container">
    <div class="heading">
      <h1 class="title">2048</h1>
      <div class="scores-container">
        <div class="score-container">0</div>
        <div class="best-container">0</div>
      </div>
    </div>

    <div class="above-game">
      <p class="game-intro">Join the numbers and get to the <strong>2048 tile!</strong></p>
      <a class="restart-button">New Game</a>
    </div>

    <div class="game-container">
      <div class="game-message">
        <p></p>
        <div class="lower">
	        <a class="keep-playing-button">Keep going</a>
          <a class="retry-button">Try again</a>
          <div class="score-sharing"></div>
        </div>
      </div>

      <div class="grid-container">
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
      </div>

      <div class="tile-container">

      </div>
    </div>

    <p class="game-explanation">
      <strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same number touch, they <strong>merge into one!</strong>
    </p>
    <hr>
    <p>
    <strong class="important">Note:</strong> This site is the official version of 2048. You can play it on your phone via <a href="http://git.io/2048">http://git.io/2048.</a> All other apps or sites are derivatives or fakes, and should be used with caution.
    </p>
    <hr>
    <p>
    Created by <a href="http://gabrielecirulli.com" target="_blank">Gabriele Cirulli.</a> Based on <a href="https://itunes.apple.com/us/app/1024!/id823499224" target="_blank">1024 by Veewo Studio</a> and conceptually similar to <a href="http://asherv.com/threes/" target="_blank">Threes by Asher Vollmer.</a>
    </p>
  </div>

  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src={% static "notfirstapp/js/json2.js"%}></script>
  <script src={% static "notfirstapp/js/bind_polyfill.js"%}></script>
  <script src={% static "notfirstapp/js/classlist_polyfill.js"%}></script>
  <script src={% static "notfirstapp/js/animframe_polyfill.js"%}></script>
  <script src={% static "notfirstapp/js/keyboard_input_manager.js"%}></script>
  <script src={% static "notfirstapp/js/html_actuator.js"%}></script>
  <script src={% static "notfirstapp/js/grid.js"%}></script>
  <script src={% static "notfirstapp/js/tile.js"%}></script>
  <script src={% static "notfirstapp/js/local_storage_manager.js"%}></script>
  <script src={% static "notfirstapp/js/game_manager.js"%}></script>
  <script src={% static "notfirstapp/js/application.js"%}></script>
  
  <script type="text/javascript" src={% static "notfirstapp/js/jquery.colorbox-min.js"%}></script>
</body>
</html>

notfirstapp/templates/notfirstapp/detail.html
{% if current_game %}
	<h1>Game List Detail</h1>
    <h3>Game Name:</h3>
    	<ul><p>&#09 {{current_game.gamename}}</p></ul>
    <h3>Created Time:</h3>
        <ul><p>&#09 {{current_game.createTime}}</p></ul>
    <h3>Players:</h3>
        {% for player in current_players %}
            <ul><p>&#09 {{player.Account_id}} as {{player.Figure_id}}</p></ul>
        {% endfor %}
{% else %}
    <p>No Contact for now.</p>
{% endif %}
<p><a href={% url 'index' %}>back to list</a></p>

notfirstapp/templates/notfirstapp/gamedetail.html
{%extends "notfirstapp/base.html"%}
{%load staticfiles%}
{%block content%}
<div id="gameinfo">
	{% if game %}
        <img id="gameposter" src="/{{appname}}{{game.fk_image.imagefile.url}}" alt={{game.fk_image.imagefile.name}}>

        <p>{{game.gamename}}</p>
        <p>{{game.createTime}}</p>
    {% else %}
        <p>No Game.</p>
    {% endif %}
</div>
<div>
	
	<a href="{{back_url}}">BACK</a>
</div>
<style type="text/css">
	#gameinfo{
		padding-top: 8em;
	}
	#gameposter{
		height: 100px;
		width: 100px;
		margin-bottom: 2em;
	}
</style>
    
{%endblock%}

notfirstapp/templates/notfirstapp/gameform.html
{%extends 'notfirstapp/base.html'%}
{%block content%}

<div id='formblock'>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        

        <input type="submit" value="Create" />
        <a class='alpha two columns' 
            href='{% url 'ImageFormPage' %}?back={{ current_path }}'>Upload New Image</a>
    </form>
<div>
<style type="text/css">
	#formblock{
		padding-top: 10em;
		padding-left: 3em;
	}

</style>

{%endblock%}

notfirstapp/templates/notfirstapp/gamelist.html
{%extends 'notfirstapp/base.html'%}
{%load staticfiles%}
    <!-- List of uploaded documents -->

{%block content%}
<div class="templatemo_portfolio" id="templatemo_portfolio">
        <h2>Our Game Library</h2>
        <p>Here is a list of the most popular games powered by Cloud Game Ranking System.<API class=""></API> </p>

        <div class="container">
            {% if game_list %}
                {% for game in game_list %}
                    {% if game %}
                        <div class="col-xs-6 col-sm-6 col-md-3 templatemo_col12">
                            <div class="portfolio-item">
                                    <div class="portfolio-thumb">
                                        {%if game.fk_image%}
                                        <img id='gameicon' src="/notfirstapp{{game.fk_image.imagefile.url}}" alt="portfolio 1">
                                        {%else%}
                                        <img src='{% static "notfirstapp/images/portfolio/1.jpg"%} alt="portfolio 1"'>
                                        {%endif%}
                                        <div class="overlay-p" >
                                            <a data-rel={% url 'ScoreRankPage' game.id%} class='colorbox-rank'>
                                                <ul>
                                                    <li>{{game.gamename}}</li>
                                                    <li class="fa fa-circle"></li>
                                                    <li class="fa fa-circle fsmall"></li>
                                                    <li class="fa fa-circle"></li>
                                                    <li class="fa fa-circle fsmall"></li>
                                                    <li class="fa fa-search fa-2x"></li>
                                                </ul>
                                            </a>
                                        </div>
                                    </div> <!-- /.portfolio-thumb -->
                                </div>
                          </div>
                    {%endif%}
                {% endfor %}
            {% else %}
                <li>Sorry, no game in this list.</li>
            {% endif %}

        </div>
        <div>
            <a href={%url 'GameFormPage'%}>Create a new game rank</a>
        </div>
  </div>

<style type="text/css">
    #gameicon{
        max-width:100%;
        height: 204px;
        /*width: auto;*/
        /*width: 65px;*/

    }
</style>

        <!-- Upload form. Note enctype attribute! -->
        <!-- <form action="{% url 'ImageListPage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.imagefile.label_tag }} {{ form.imagefile.help_text }}</p>
            <p>
                {{ form.imagefile.errors }}
                {{ form.imagefile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form> -->
{%endblock content%}

{%block endscript%}

<link href={% static "notfirstapp/css/colorbox.css"%} rel="stylesheet">
<script type="text/javascript" src={% static "notfirstapp/js/jquery.colorbox-min.js"%}></script>
<script type="text/javascript">
    $('.colorbox-rank').bind('click',function(){
        var tile=$(this)
        var url=tile.data("rel");
        $.colorbox({href:url});    
    });

</script>
{%endblock endscript%}

{%block about%}{%endblock about%}

notfirstapp/templates/notfirstapp/imagedetial.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>   
    </head>
    <body>
    <!-- List of uploaded documents -->
    {% if image %}
        <img src="/{{appname}}{{image.imagefile.url}}" alt={{image.imagefile.name}}></img>
    {% else %}
        <p>No image.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <!-- <form action="{% url 'ImageListPage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.imagefile.label_tag }} {{ form.imagefile.help_text }}</p>
            <p>
                {{ form.imagefile.errors }}
                {{ form.imagefile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form> -->
    </body>
</html> 

notfirstapp/templates/notfirstapp/imageform.html
{%extends 'notfirstapp/base.html'%}
    <!-- List of uploaded documents -->
    {%block content%}

    <div id="imageuploadform">
        {% if uploaded %}
        <ul>
        {% for uploadimg in uploaded %}
            <li><a href="/notfirstapp{{ uploadimg.imagefile.url }}">{{ uploadimg.imagefile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No image.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'ImageFormPage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_ul }}
            <p><input type="submit" value="Upload" /></p>
        </form>
    </div>

    <style type="text/css">
        #imageuploadform{
            padding-top: 8em;   
            padding-left: 3em;
        }
    </style>
    {%endblock%}

notfirstapp/templates/notfirstapp/imagelist.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Image List View</title>   
    </head>
    <body>
    <!-- List of uploaded documents -->
    {% if imagelist %}
        <ul>
        {% for image in imagelist %}
            <li><a href="{% url 'ImageDetailPage' image.id%}">{{ image.imagefile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No image.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <!-- <form action="{% url 'ImageListPage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.imagefile.label_tag }} {{ form.imagefile.help_text }}</p>
            <p>
                {{ form.imagefile.errors }}
                {{ form.imagefile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form> -->
    </body>
</html> 

notfirstapp/templates/notfirstapp/index2.html
{% if current_game %}
	<h1>Game List</h1>
    <ul>
    {% for p in current_game %}
        <li><a href={% url 'DetailPage' p.id%}>{{p}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Contact for now.</p>
{% endif %}
<p><a href={% url 'CreatePage'%}>Create new contact</a></p>

notfirstapp/templates/notfirstapp/loginframe.html
{%extends 'notfirstapp/base.html'%}
{%load staticfiles%}


{%if user.is_anonymous%}
	{%block content%}}
	<!DOCTYPE html>
	<div id="loginView">
	<head>

		<!-- Basics -->
		
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		
		<title>Login</title>

		<!-- CSS -->
		
		<link rel="stylesheet" href={%static 'notfirstapp/css/reset.css'%}>
		<link rel="stylesheet" href={%static 'notfirstapp/css/animate.css'%}>
		<link rel="stylesheet" href={%static 'notfirstapp/css/styles.css'%}>
		
	</head>

		<!-- Main HTML -->
		
	<body>
		
		<!-- Begin Page Content -->
		
		<div id="container">

		{% if form.errors %}
		<p>Your username and password didn't match. Please try again. {{form.errors}}</p>
		{% endif %}
			
			<form action={% url 'django.contrib.auth.views.login' %} method="post">
				{% csrf_token %}
			
			<label for="name">Username:</label>
			
			<input type="name" id='id_username' name='username'>
			
			<label for="username">Password:</label>
			
			<p><a href="#">Forgot your password?</a>
			
			<input type="password" id='id_password' name='password'>
			
			<div id="lower">
			
			<input type="checkbox"><label class="check" for="checkbox">Keep me logged in</label>
			
			<input type='button' value='SignUp' onclick="location.href='{%url 'SignUpPage'%}'">
			<input type="submit" value="LogIn">
			<input type="hidden" name="next" value="{{ next }}" />
			
			</div>
			
			</form>
					<p>ray:1 for testing</p>
		</div>
		
		
		<!-- End Page Content -->
		
	</body>
	</div>
	<style type="text/css">
		#loginView{

			padding-top: 10em;
		}
	</style>

	{%if alert%}
	<script type="text/javascript">
		alert('{{alert}}');
	</script>
	{%endif%}
	{%endblock content%}

{%else%}

{%endif%}


	
	
	
	
	
		
	

notfirstapp/templates/notfirstapp/logout.html
{%extends 'notfirstapp/base.html'%}
{%load staticfiles%}

{%block content%}}
<!DOCTYPE html>
<div id='logoutView'>
	<p2> Goodbye!</p2>
</div>
<style type="text/css">
	#logoutView{

		padding-top: 10em;
		.p2{

			/*font-size: 10;*/
		}
	}
</style>

{%endblock content%}

notfirstapp/templates/notfirstapp/profile.html
{%extends 'notfirstapp/base.html'%}

{%block content%}
<div id="userinfocontainer">
	{%if user.is_authenticated%}}
	<h2> Welcome</h2>

	<ul>{{user.username}}</ul>
	<ul>{{user.email}}</ul>
	{{%endif%}
</div>
<style type="text/css">
	#userinfocontainer{
		padding-top: 10em;
	}
</style>
{%endblock%}

notfirstapp/templates/notfirstapp/ranklist.html
{%if rank_list%}
<h2>{{game.gamename}}</h2>
<table style="width:450px">
	<tr>
		<th>#</th>
		<th>Figure</th>
		<th>Score</th>
		<th>Achieve Time</th>
	</tr>
	{%for rank in rank_list%}
	<tr>
		<td>{{rank.rank}}</td>
		<td>{{rank.Figure_id.name}}</td>
		<td>{{rank.score}}</td>
		<td>{{rank.achieveTime}}</td>
	</tr>
	{%endfor%}
</table> 
{%else%}
<h2>{{game.gamename}}</h2>
<p>No rank record for this game now.</p>
{%endif%}

notfirstapp/templates/notfirstapp/signup.html
{%extends 'notfirstapp/base.html'%}
{%load staticfiles%}


	{%block content%}

	<header>

		<!-- Basics -->
		
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		
		<title>Login</title>

		<!-- CSS -->
		
		<link rel="stylesheet" href={%static 'notfirstapp/css/reset.css'%}>
		<link rel="stylesheet" href={%static 'notfirstapp/css/animate.css'%}>
		<link rel="stylesheet" href={%static 'notfirstapp/css/styles.css'%}>
		
	</header>

		<!-- Main HTML -->
		

		
		<!-- Begin Page Content -->
		
		<div id="container">

		{% if form.errors %}
		{%for error, info in form.errors.items%}
			<p>{{error}} -- {{info}}</p>
		{%endfor%}

		{% endif %}
			
			<form action={% url 'SignUpPage' %} method="post">
				{% csrf_token %}
			
			<label for="name">Username*:</label>
			
			<input type="name" id='id_username' name='username' value='{{form.data.username}}'>
			
			<label for="username">Password*:</label>
			
			<input type="password" id='id_password' name='password' value=''>

			<label for="email">Email:</label>
			
			<input type="email" id='id_email' name='email' value='{{form.data.email}}'>

			<label for="firstname">Firstname:</label>
			
			<input type="text" id='id_firstname' name='firstname' value='{{form.data.firstname}}'>

			<label for="lastname">Lastname:</label>
			
			<input type="text" id='id_lastname' name='lastname' value='{{form.data.lastname}}'>
			
			<div id="lower">
			
			<!-- <input type="checkbox"><label class="check" for="checkbox">Keep me logged in</label> -->
			
			<input type='reset'>
			<input type="submit" value="Register">
			<!-- <input type="hidden" name="next" value="{{ next }}" /> -->
			
			</div>
			
			</form>
		</div>
		
		
		<!-- End Page Content -->
		

	<style type="text/css">
		#loginView{

			padding-top: 10em;
		}
	</style>

	<style type="text/css">
		#container{

			height: auto;
		}
	</style>
	{%endblock content%}


	
	
	
	
	
		
	